export const MEDICINE_TYPES = [
  { value: "tablet", label: "Tablet" },
  { value: "capsule", label: "Capsule" },
  { value: "injection", label: "Injection" },
  { value: "syrup", label: "Syrup" },
  { value: "drops", label: "Drops" },
  { value: "cream", label: "Cream" },
  { value: "ointment", label: "Ointment" },
]

export const DOSAGE_UNITS = [
  { value: "mg", label: "mg" },
  { value: "g", label: "g" },
  { value: "ml", label: "ml" },
  { value: "mcg", label: "mcg" },
  { value: "IU", label: "IU" },
]

export const COMMON_MEDICINES = [
  "MIXEL",
  "POLYMALT-F",
  "QSARTEN",
  "MEDITON",
  "CYCIN",
  "DAYFORT",
  "DYPIME",
  "VINZET",
  "MOLAM",
  "CEBECT",
  "MEVET",
  "MILITRIUM",
  "KINETON",
  "ECTAFIN ",
  "ABBACUS ",
  "AZITMA",
  "ONATO",
  "TPENTA IR ",
  "MONTIKA ",
  "PERIDONE",
  "MOFEST",
  "OXIDIL",
  "NIVADOR",
  "LACASIL",
  "TRIMETABOL",
  "SLATE",
  "CARICEF",
  "BRINO",
  "EMFLOX",
  "SOLPLUS",
  "CYNTOL",
  "PRUJEX",
  "DIRICIN",
  "MOLOX",
  "LEVOCIL ",
  "HELOWIC",
  "LACASIA ",
  "ACASIA",
  "REALOZA DR",
  "BACTCID ",
  "DEEBO",
  "XETOPLUS",
  "OVELCIN",
  "LAXCELL",
  "MOFLOTEN",
  "KETOCELL",
  "URISTAT ",
  "ZANTUM",
  "MIRABET ",
  "VTIG PLUS",
  "VEZITIC ",
  "KETORIDE",
  "MAXFLOW",
  "MAXFLOW-D",
  "EZUMAC ",
  "CYSTALGON",
  "CALAMOX",
  "PREGY",
  "EFFIFLOX",
  "NOVIDATE",
  "TONOFLEX-P",
  "2SUM",
  "MOLOX",
  "ANTIAL",
  "ORGLU",
  "ONTIVE",
  "SILIDATE",
  "ITP",
  "DICLORAN",
  "KINZ",
  "SILDOSO",
  "VITIG PLUS",
  "VITIG",
  "C-ONE",
  "URIZAK",
  "BONE-CARE",
  "FERRO-ONE",
  "MEQUINE",
  "QUSPAR",
  "BONE-CARE-C",
  "BALATINE",
  "CARNEO",
  "ESOIN",
  "NUBREL-FORTE",
  "BRUFFEN",
  "SANGIBON",
  "GAVACISON",
  "PALMONIVE",
  "CITRALKA",
  "TORALAC",
  "PROVAS"

]

export const DOSAGE_PATTERNS = [
  { value: "1+0+0", label: "1+0+0 (Morning only)" },
  { value: "0+0+1", label: "0+0+1 (Evening only)" },
  { value: "1+0+1", label: "1+0+1 (Morning & Evening)" },
  { value: "1+1+1", label: "1+1+1 (Three times daily)" },
  { value: "2+0+0", label: "2+0+0 (2 Morning)" },
  { value: "0+0+2", label: "0+0+2 (2 Evening)" },
  { value: "2+0+2", label: "2+0+2 (2 Morning & 2 Evening)" },
  { value: "1+1+0", label: "1+1+0 (Morning & Afternoon)" },
  { value: "0+1+1", label: "0+1+1 (Afternoon & Evening)" },
]
